---
abstract: 'Decodes and encodes DOCSIS config-files'
author:
  - 'Jan Henning Thorsen, C<< <pm at flodhest.net> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.9
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DOCSIS-ConfigFile
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Digest::HMAC_MD5: 1
  Digest::MD5: 2.39
  FindBin: 1.5
  Getopt::Long: 2
  Log::Log4perl: 1.26
  Math::BigInt: 1.89
  Socket: 1.82
  bytes: 1
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Docsis-ConfigFile
  license: http://dev.perl.org/licenses/
  repository: http://github.com/jhthorsen/docsis-configfile
version: 0.5901
