---
abstract: 'Decodes and encodes DOCSIS config-files'
author:
  - 'Jan Henning Thorsen, C<< <pm at flodhest.net> >>'
build_requires:
  Data::Dumper: 2.1
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.9
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DOCSIS-ConfigFile
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Digest::HMAC_MD5: 1
  Digest::MD5: 2.3
  Math::BigInt: 1.8
  Socket: 1.5
  autodie: 2
  bytes: 1
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=DOCSIS-ConfigFile
  homepage: http://search.cpan.org/dist/DOCSIS-ConfigFile
  license: http://dev.perl.org/licenses/
  repository: git://github.com//home/repositories/docsis-configfile.git
version: 0.60
