# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DOCSIS::ConfigFile
version:      0.02
version_from: lib/DOCSIS/ConfigFile.pm
installdirs:  site
requires:
    Log::Log4perl: 0
    Math::BigInt:  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01

