---
abstract: 'Decodes and encodes DOCSIS config-files'
author:
  - 'Jan Henning Thorsen, C<< <pm at flodhest.net> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DOCSIS-ConfigFile
no_index:
  directory:
    - examples
    - inc
    - t
recommends:
  Log::Log4perl: 0
requires:
  Digest::HMAC_MD5: 0
  Digest::MD5: 0
  Getopt::Euclid: 0
  Math::BigInt: 0
  Socket: 0
  bytes: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.58
