---
abstract: 'Decodes and encodes DOCSIS config files'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  Test::More: '0.8'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.143240'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DOCSIS-ConfigFile
no_index:
  directory:
    - t
    - inc
requires:
  Digest::HMAC_MD5: '1.00'
  Digest::MD5: '2.30'
  Digest::SHA: '5.00'
  Math::BigInt: '1.80'
  Socket: '1.50'
  bytes: '1.00'
resources:
  bugtracker: https://github.com/jhthorsen/docsis-configfile/issues
  homepage: https://github.com/jhthorsen/docsis-configfile
  repository: https://github.com/jhthorsen/docsis-configfile.git
version: '0.66'
